### ISSUE TITLE
Facebook Crawling API

### ISSUE THREAD

**Issue by nuxlear** [nuxlear/military-letter-crawler#6]
- 페이스북에 Graph API라는 이름으로 기능 제공중
  - https://developers.facebook.com/docs/graph-api?locale=ko_KR

위 API 사용 신청부터 자동화해서 코드로 가능한 지 확인 부탁함. @DropFL @S4nop

**Comment by DropFL** [comment]
Graph API의 경우 앱을 등록하고 관련된 토큰을 관리해야 하는데, 그러한 작업을 시간 내에 하기엔 어려움이 있어 스펙아웃됨

+

로그인 이후 **홈페이지 접속 시 표시되는 뉴스피드**는 Graph API를 통해 가져올 수 없음.

Graph API에서 말하는 사용자 피드는 **해당 사용자가 게시한 피드**를 말하는 것으로, 위와는 다름
